/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author newik
 */
public class JFrameRotaCalculada extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRotaCalculada
     */
    public JFrameRotaCalculada() {
        
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Dist = new javax.swing.JLabel();
        jTextField_Distancia = new javax.swing.JTextField();
        jTextField_KmRodado = new javax.swing.JTextField();
        jLabel_KmRodado = new javax.swing.JLabel();
        jLabel_CustoTrecho = new javax.swing.JLabel();
        jTextField_CustoTrecho = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rota calculada com sucesso");

        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("A rota foi calculada com sucesso, abaixo segue o resultado do custo:");
        jLabel_Titulo.setToolTipText("");

        jLabel_Dist.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Dist.setText("Quilometragem rodada:");

        jTextField_Distancia.setEditable(false);
        jTextField_Distancia.setText("0.0 Km");

        jTextField_KmRodado.setEditable(false);
        jTextField_KmRodado.setText("R$ 0.00");

        jLabel_KmRodado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_KmRodado.setText("Custo por Km rodado:");

        jLabel_CustoTrecho.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_CustoTrecho.setText("Custo toal do trecho:");

        jTextField_CustoTrecho.setEditable(false);
        jTextField_CustoTrecho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField_CustoTrecho.setText("R$ 0.00");

        jButton_Ok.setText("Ok");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_Dist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_KmRodado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_CustoTrecho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_CustoTrecho)
                            .addComponent(jTextField_KmRodado)
                            .addComponent(jTextField_Distancia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Dist)
                    .addComponent(jTextField_Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_KmRodado)
                    .addComponent(jTextField_KmRodado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_CustoTrecho, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_CustoTrecho, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton_Ok)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_OkActionPerformed

    public void setJTextField_Distancia(double distancia){
        jTextField_Distancia.setText(distancia+" Km");
    }
    
    public void setJTextField_KmRodado(double custoPorKm){
        jTextField_KmRodado.setText("R$ "+ custoPorKm);
    }
    
    public void setJTextField_CustoTrecho(double custo){
        jTextField_CustoTrecho.setText("R$ "+ custo);
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JLabel jLabel_CustoTrecho;
    private javax.swing.JLabel jLabel_Dist;
    private javax.swing.JLabel jLabel_KmRodado;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_CustoTrecho;
    private javax.swing.JTextField jTextField_Distancia;
    private javax.swing.JTextField jTextField_KmRodado;
    // End of variables declaration//GEN-END:variables
}
