/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 *
 * @author newik
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuPrincipal
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparatorTitulo = new javax.swing.JSeparator();
        jPanelSelection = new javax.swing.JPanel();
        jLabelSelecionar = new javax.swing.JLabel();
        jButtonCalcRota = new javax.swing.JButton();
        jButtonSimulaRota = new javax.swing.JButton();
        jButtonDadosEst = new javax.swing.JButton();
        jSeparatorVersao = new javax.swing.JSeparator();
        jLabelVersao = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        JMenuFile = new javax.swing.JMenu();
        jMenuItemCalcRota = new javax.swing.JMenuItem();
        jMenuItemSimulaRota = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItemDadosEst = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemConfig = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Transporte Interestadual de Cargas");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Sistema de Transporte Interestadual de Cargas");

        jPanelSelection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSelection.setForeground(new java.awt.Color(204, 204, 204));

        jLabelSelecionar.setText("Por favor, selecione uma das opções abaixo:");

        jButtonCalcRota.setText("Calcular Trechos");
        jButtonCalcRota.setPreferredSize(new java.awt.Dimension(150, 50));

        jButtonSimulaRota.setText("Registrar Trecho");
        jButtonSimulaRota.setPreferredSize(new java.awt.Dimension(150, 50));

        jButtonDadosEst.setText("Dados Estatísticos...");
        jButtonDadosEst.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout jPanelSelectionLayout = new javax.swing.GroupLayout(jPanelSelection);
        jPanelSelection.setLayout(jPanelSelectionLayout);
        jPanelSelectionLayout.setHorizontalGroup(
            jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelecionar)
                    .addGroup(jPanelSelectionLayout.createSequentialGroup()
                        .addComponent(jButtonCalcRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSimulaRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDadosEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSelectionLayout.setVerticalGroup(
            jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSimulaRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDadosEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabelVersao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersao.setText("Versão 0.1 - 24 / mar / 2023");

        JMenuFile.setText("File");

        jMenuItemCalcRota.setText("Calcular trechos existentes...");
        JMenuFile.add(jMenuItemCalcRota);

        jMenuItemSimulaRota.setText("Cadastar novo trecho...");
        JMenuFile.add(jMenuItemSimulaRota);

        jMenu.add(JMenuFile);

        jMenuView.setText("View");

        jMenuItemDadosEst.setText("Estatísitica sobre trechos realizados...");
        jMenuView.add(jMenuItemDadosEst);

        jMenu.add(jMenuView);

        jMenuEdit.setText("Edit");

        jMenuItemConfig.setText("Alterar parâmetros...");
        jMenuEdit.add(jMenuItemConfig);

        jMenuItemAbout.setText("About...");
        jMenuEdit.add(jMenuItemAbout);

        jMenu.add(jMenuEdit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorTitulo)
                    .addComponent(jLabelVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorVersao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVersao)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Deixa publico o acesso ao clique do menuItem "About..."
    public JMenuItem getJMenuItemAbout(){
        return jMenuItemAbout;
    }
    // Deixa publico o acesso ao clique do menuItem "CalcRota"
    public JMenuItem getJMenuCalcRota(){
        return jMenuItemCalcRota;
    }
    // Deixa publico o acesso ao clique do botão "CalcRota"
    public JButton getJButtonCalcRota(){
        return jButtonCalcRota;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuFile;
    private javax.swing.JButton jButtonCalcRota;
    private javax.swing.JButton jButtonDadosEst;
    private javax.swing.JButton jButtonSimulaRota;
    private javax.swing.JLabel jLabelSelecionar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVersao;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemCalcRota;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenuItem jMenuItemDadosEst;
    private javax.swing.JMenuItem jMenuItemSimulaRota;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPanelSelection;
    private javax.swing.JSeparator jSeparatorTitulo;
    private javax.swing.JSeparator jSeparatorVersao;
    // End of variables declaration//GEN-END:variables
}
