package View;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;


/**
 *
 * @author newik
 */
public class JFrameCadastrarTransporte extends javax.swing.JFrame {

    public JFrameCadastrarTransporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jSeparator_Titulo = new javax.swing.JSeparator();
        jLabel_TrechosResgistrados = new javax.swing.JLabel();
        jButton_RemoverTrechoTabela = new javax.swing.JButton();
        jScrollPane_TabelaTrechos = new javax.swing.JScrollPane();
        jTable_TabelaTrechos = new javax.swing.JTable();
        jLabel_CidadeOrigem = new javax.swing.JLabel();
        jComboBox_CidadeOrigem = new javax.swing.JComboBox<>();
        jLabel_CidadeDestino = new javax.swing.JLabel();
        jComboBox_CidadeDestino = new javax.swing.JComboBox<>();
        jButton_CadastrarTrecho = new javax.swing.JButton();
        jSeparator_TrechosRegistrados = new javax.swing.JSeparator();
        jPanel_Produtos = new javax.swing.JPanel();
        jLabel_ListaProdutos = new javax.swing.JLabel();
        jButton_RemoverProdutoTabela = new javax.swing.JButton();
        jLabel_ListaTransportes = new javax.swing.JLabel();
        jComboBox_ListaTransportes = new javax.swing.JComboBox<>();
        jButton_CadastrarProduto = new javax.swing.JButton();
        jScrollPane_TabelaProdutos = new javax.swing.JScrollPane();
        jTable_TabelaProdutos = new javax.swing.JTable();
        jSeparator_Produtos = new javax.swing.JSeparator();
        jButton_CalcularTransporte = new javax.swing.JButton();
        jInternalFrame_ResultadoTransporte = new javax.swing.JInternalFrame();
        jLabel_NomeRota = new javax.swing.JLabel();
        jTextField_NomeRota = new javax.swing.JTextField();
        jLabel_DistanciaTotal = new javax.swing.JLabel();
        jTextField_DistanciaTotal = new javax.swing.JTextField();
        jLabel_ValorTotal = new javax.swing.JLabel();
        jTextField_ValorTotal = new javax.swing.JTextField();
        jLabel_ValorUnitMedio = new javax.swing.JLabel();
        jTextField_ValorUnitMedio = new javax.swing.JTextField();
        jLabel_ListaCaminhoes = new javax.swing.JLabel();
        jScrollPane_ListaCaminhoes = new javax.swing.JScrollPane();
        jTextArea_ListaCaminhoes = new javax.swing.JTextArea();
        jButton_CalcularNovaRota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar novo transporte");

        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Cadastro de Transporte");

        jLabel_TrechosResgistrados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_TrechosResgistrados.setText("Lista de trechos registrados:");

        jButton_RemoverTrechoTabela.setText("Remover rota selecionada...");
        jButton_RemoverTrechoTabela.setEnabled(false);

        jTable_TabelaTrechos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cidade Origem", "Cidade Destino", "Distância"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_TabelaTrechos.setName("tabelaTrechos"); // NOI18N
        jScrollPane_TabelaTrechos.setViewportView(jTable_TabelaTrechos);

        jLabel_CidadeOrigem.setText("Adiconar cidade de origem:");

        jLabel_CidadeDestino.setText("Adiconar cidade de destino:");

        jComboBox_CidadeDestino.setToolTipText("");

        jButton_CadastrarTrecho.setText("Cadastrar Trecho");

        jPanel_Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_Produtos.setEnabled(false);

        jLabel_ListaProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_ListaProdutos.setText("Lista de produtos cadastrados:");

        jButton_RemoverProdutoTabela.setText("Remover produto selecionado...");
        jButton_RemoverProdutoTabela.setEnabled(false);

        jLabel_ListaTransportes.setText("Atrelar peso ao transporte:");

        jComboBox_ListaTransportes.setEnabled(false);

        jButton_CadastrarProduto.setText("Novo produto");
        jButton_CadastrarProduto.setEnabled(false);

        jTable_TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Qtd.", "Peso", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_TabelaProdutos.setEnabled(false);
        jScrollPane_TabelaProdutos.setViewportView(jTable_TabelaProdutos);

        javax.swing.GroupLayout jPanel_ProdutosLayout = new javax.swing.GroupLayout(jPanel_Produtos);
        jPanel_Produtos.setLayout(jPanel_ProdutosLayout);
        jPanel_ProdutosLayout.setHorizontalGroup(
            jPanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProdutosLayout.createSequentialGroup()
                .addComponent(jLabel_ListaProdutos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane_TabelaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProdutosLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_ProdutosLayout.createSequentialGroup()
                        .addGroup(jPanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_ListaTransportes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jComboBox_ListaTransportes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_CadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_RemoverProdutoTabela)))
        );
        jPanel_ProdutosLayout.setVerticalGroup(
            jPanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProdutosLayout.createSequentialGroup()
                .addComponent(jLabel_ListaProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProdutosLayout.createSequentialGroup()
                        .addComponent(jLabel_ListaTransportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_ListaTransportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_CadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_TabelaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_RemoverProdutoTabela)
                .addContainerGap())
        );

        jSeparator_Produtos.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton_CalcularTransporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_CalcularTransporte.setText("Calcular Transporte");
        jButton_CalcularTransporte.setToolTipText("É necessário adicionar uma lista de produtos e ter no mínimo uma rota para calcular.");
        jButton_CalcularTransporte.setEnabled(false);

        jInternalFrame_ResultadoTransporte.setTitle("Resultado do Transporte");
        jInternalFrame_ResultadoTransporte.setToolTipText("");
        jInternalFrame_ResultadoTransporte.setEnabled(false);
        jInternalFrame_ResultadoTransporte.setVisible(true);

        jLabel_NomeRota.setText("Nome Rota:");

        jTextField_NomeRota.setEditable(false);
        jTextField_NomeRota.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_NomeRota.setText("SANTA MARIA - PORTO ALEGRE");

        jLabel_DistanciaTotal.setText("Distância Total:");

        jTextField_DistanciaTotal.setEditable(false);
        jTextField_DistanciaTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_DistanciaTotal.setText("300 Km");

        jLabel_ValorTotal.setText("Valor Total:");

        jTextField_ValorTotal.setEditable(false);
        jTextField_ValorTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_ValorTotal.setText("R$ 300.20");

        jLabel_ValorUnitMedio.setText("Valor Un. Médio:");

        jTextField_ValorUnitMedio.setEditable(false);
        jTextField_ValorUnitMedio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_ValorUnitMedio.setText("R$ 20.20");

        jLabel_ListaCaminhoes.setText("Lista de Caminhões:");

        jScrollPane_ListaCaminhoes.setToolTipText("");
        jScrollPane_ListaCaminhoes.setName(""); // NOI18N

        jTextArea_ListaCaminhoes.setEditable(false);
        jTextArea_ListaCaminhoes.setColumns(20);
        jTextArea_ListaCaminhoes.setRows(5);
        jScrollPane_ListaCaminhoes.setViewportView(jTextArea_ListaCaminhoes);

        jButton_CalcularNovaRota.setText("Calcular Nova Rota");
        jButton_CalcularNovaRota.setEnabled(false);

        javax.swing.GroupLayout jInternalFrame_ResultadoTransporteLayout = new javax.swing.GroupLayout(jInternalFrame_ResultadoTransporte.getContentPane());
        jInternalFrame_ResultadoTransporte.getContentPane().setLayout(jInternalFrame_ResultadoTransporteLayout);
        jInternalFrame_ResultadoTransporteLayout.setHorizontalGroup(
            jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_ResultadoTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame_ResultadoTransporteLayout.createSequentialGroup()
                        .addGroup(jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_DistanciaTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_NomeRota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DistanciaTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ValorTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ValorTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ValorUnitMedio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ValorUnitMedio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ListaCaminhoes)
                            .addComponent(jScrollPane_ListaCaminhoes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jButton_CalcularNovaRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_NomeRota))
                .addGap(9, 9, 9))
        );
        jInternalFrame_ResultadoTransporteLayout.setVerticalGroup(
            jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_ResultadoTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_NomeRota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_NomeRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DistanciaTotal)
                    .addComponent(jLabel_ListaCaminhoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_ResultadoTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame_ResultadoTransporteLayout.createSequentialGroup()
                        .addComponent(jTextField_DistanciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_ValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_ValorUnitMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ValorUnitMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane_ListaCaminhoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CalcularNovaRota)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_TrechosResgistrados, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addGap(162, 162, 162)
                        .addComponent(jButton_RemoverTrechoTabela))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CalcularTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jInternalFrame_ResultadoTransporte)))
                    .addComponent(jScrollPane_TabelaTrechos)
                    .addComponent(jSeparator_Titulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator_TrechosRegistrados)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_CidadeOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jComboBox_CidadeOrigem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_CidadeDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jComboBox_CidadeDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton_CadastrarTrecho, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TrechosResgistrados)
                    .addComponent(jButton_RemoverTrechoTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_TabelaTrechos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CidadeOrigem)
                            .addComponent(jLabel_CidadeDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_CidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_CidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_CadastrarTrecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator_TrechosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Produtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator_Produtos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_CalcularTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame_ResultadoTransporte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButton_CadastrarProduto() {
        return jButton_CadastrarProduto;
    }

    public JButton getjButton_CadastrarTrecho() {
        return jButton_CadastrarTrecho;
    }

    public JButton getjButton_CalcularNovaRota() {
        return jButton_CalcularNovaRota;
    }

    public JButton getjButton_CalcularTransporte() {
        return jButton_CalcularTransporte;
    }

    public JButton getjButton_RemoverProdutoTabela() {
        return jButton_RemoverProdutoTabela;
    }

    public JButton getjButton_RemoverTrechoTabela() {
        return jButton_RemoverTrechoTabela;
    }

    public JComboBox<String> getjComboBox_CidadeDestino() {
        return jComboBox_CidadeDestino;
    }

    public JComboBox<String> getjComboBox_CidadeOrigem() {
        return jComboBox_CidadeOrigem;
    }

    public JComboBox<String> getjComboBox_ListaTransportes() {
        return jComboBox_ListaTransportes;
    }

    public JTable getjTable_TabelaProdutos() {
        return jTable_TabelaProdutos;
    }

    public JTable getjTable_TabelaTrechos() {
        return jTable_TabelaTrechos;
    }

    public JTextArea getjTextArea_ListaCaminhoes() {
        return jTextArea_ListaCaminhoes;
    }

    public JTextField getjTextField_DistanciaTotal() {
        return jTextField_DistanciaTotal;
    }

    public JTextField getjTextField_NomeRota() {
        return jTextField_NomeRota;
    }

    public JTextField getjTextField_ValorTotal() {
        return jTextField_ValorTotal;
    }

    public JTextField getjTextField_ValorUnitMedio() {
        return jTextField_ValorUnitMedio;
    }
    
    public void atualizarCidades(String[] cidades){
        jComboBox_CidadeOrigem.setModel(new DefaultComboBoxModel<>(cidades));
        jComboBox_CidadeDestino.setModel(new DefaultComboBoxModel<>(cidades));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastrarProduto;
    private javax.swing.JButton jButton_CadastrarTrecho;
    private javax.swing.JButton jButton_CalcularNovaRota;
    private javax.swing.JButton jButton_CalcularTransporte;
    private javax.swing.JButton jButton_RemoverProdutoTabela;
    private javax.swing.JButton jButton_RemoverTrechoTabela;
    private javax.swing.JComboBox<String> jComboBox_CidadeDestino;
    private javax.swing.JComboBox<String> jComboBox_CidadeOrigem;
    private javax.swing.JComboBox<String> jComboBox_ListaTransportes;
    private javax.swing.JInternalFrame jInternalFrame_ResultadoTransporte;
    private javax.swing.JLabel jLabel_CidadeDestino;
    private javax.swing.JLabel jLabel_CidadeOrigem;
    private javax.swing.JLabel jLabel_DistanciaTotal;
    private javax.swing.JLabel jLabel_ListaCaminhoes;
    private javax.swing.JLabel jLabel_ListaProdutos;
    private javax.swing.JLabel jLabel_ListaTransportes;
    private javax.swing.JLabel jLabel_NomeRota;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_TrechosResgistrados;
    private javax.swing.JLabel jLabel_ValorTotal;
    private javax.swing.JLabel jLabel_ValorUnitMedio;
    private javax.swing.JPanel jPanel_Produtos;
    private javax.swing.JScrollPane jScrollPane_ListaCaminhoes;
    private javax.swing.JScrollPane jScrollPane_TabelaProdutos;
    private javax.swing.JScrollPane jScrollPane_TabelaTrechos;
    private javax.swing.JSeparator jSeparator_Produtos;
    private javax.swing.JSeparator jSeparator_Titulo;
    private javax.swing.JSeparator jSeparator_TrechosRegistrados;
    private javax.swing.JTable jTable_TabelaProdutos;
    private javax.swing.JTable jTable_TabelaTrechos;
    private javax.swing.JTextArea jTextArea_ListaCaminhoes;
    private javax.swing.JTextField jTextField_DistanciaTotal;
    private javax.swing.JTextField jTextField_NomeRota;
    private javax.swing.JTextField jTextField_ValorTotal;
    private javax.swing.JTextField jTextField_ValorUnitMedio;
    // End of variables declaration//GEN-END:variables
}
