/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author newik
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuPrincipal
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparatorTitulo = new javax.swing.JSeparator();
        jPanelSelection = new javax.swing.JPanel();
        jLabelSelecionar = new javax.swing.JLabel();
        jButton_SimularRota = new javax.swing.JButton();
        jButton_CalcularRota = new javax.swing.JButton();
        jButton_DadosEstatistica = new javax.swing.JButton();
        jSeparatorVersao = new javax.swing.JSeparator();
        jLabelVersao = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        JMenuFile = new javax.swing.JMenu();
        jMenuItem_SimularRota = new javax.swing.JMenuItem();
        jMenuItem_CalcularRota = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Sair = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItem_DadosEstatistica = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemConfig = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Transporte Interestadual de Cargas");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Sistema de Transporte Interestadual de Cargas");

        jPanelSelection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSelection.setForeground(new java.awt.Color(204, 204, 204));

        jLabelSelecionar.setText("Por favor, selecione uma das opções abaixo:");

        jButton_SimularRota.setText("Consultar Trechos");
        jButton_SimularRota.setEnabled(false);
        jButton_SimularRota.setPreferredSize(new java.awt.Dimension(150, 50));

        jButton_CalcularRota.setText("Cadastrar Transporte");
        jButton_CalcularRota.setEnabled(false);
        jButton_CalcularRota.setPreferredSize(new java.awt.Dimension(150, 50));

        jButton_DadosEstatistica.setText("Dados Estatísticos");
        jButton_DadosEstatistica.setEnabled(false);
        jButton_DadosEstatistica.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout jPanelSelectionLayout = new javax.swing.GroupLayout(jPanelSelection);
        jPanelSelection.setLayout(jPanelSelectionLayout);
        jPanelSelectionLayout.setHorizontalGroup(
            jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelecionar)
                    .addGroup(jPanelSelectionLayout.createSequentialGroup()
                        .addComponent(jButton_SimularRota, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_CalcularRota, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_DadosEstatistica, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSelectionLayout.setVerticalGroup(
            jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_DadosEstatistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CalcularRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SimularRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelVersao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersao.setText("Versão 0.3 - 26 / mar / 2023");

        JMenuFile.setText("File");

        jMenuItem_SimularRota.setText("Consultar rota por modalidade...");
        jMenuItem_SimularRota.setEnabled(false);
        JMenuFile.add(jMenuItem_SimularRota);

        jMenuItem_CalcularRota.setText("Cadastrar novo transporte...");
        jMenuItem_CalcularRota.setToolTipText("");
        jMenuItem_CalcularRota.setEnabled(false);
        JMenuFile.add(jMenuItem_CalcularRota);
        JMenuFile.add(jSeparator);

        jMenuItem_Sair.setText("Sair...");
        jMenuItem_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SairActionPerformed(evt);
            }
        });
        JMenuFile.add(jMenuItem_Sair);

        jMenu.add(JMenuFile);

        jMenuView.setText("View");

        jMenuItem_DadosEstatistica.setText("Dados sobre rotas já realizadas...");
        jMenuItem_DadosEstatistica.setEnabled(false);
        jMenuView.add(jMenuItem_DadosEstatistica);

        jMenu.add(jMenuView);

        jMenuEdit.setText("Edit");

        jMenuItemConfig.setText("Alterar parâmetros...");
        jMenuEdit.add(jMenuItemConfig);

        jMenuItemAbout.setText("About...");
        jMenuEdit.add(jMenuItemAbout);

        jMenu.add(jMenuEdit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorTitulo)
                    .addComponent(jLabelVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorVersao)
                    .addComponent(jPanelSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVersao)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Caso o usuario clicar no botõa de sair mostra uma mensagem de confirmação
    private void jMenuItem_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SairActionPerformed
        int confirm = JOptionPane.showOptionDialog(this,
                        "Você tem certeza que quer sair da aplicação?",
                        "Deseja realmente sair?", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
    }//GEN-LAST:event_jMenuItem_SairActionPerformed

    //
    public JButton getjButton_SimularRota() {
        return jButton_SimularRota;
    }
    public JMenuItem getjMenuItem_SimularRota() {
        return jMenuItem_SimularRota;
    }
    
    //
    public JButton getjButton_CalcularRota() {
        return jButton_CalcularRota;
    }
    public JMenuItem getjMenuItem_CalcularRota() {
        return jMenuItem_CalcularRota;
    }
    
    //
    public JButton getjButton_DadosEstatistica() {
        return jButton_DadosEstatistica;
    }
    public JMenuItem getjMenuItem_DadosEst() {
        return jMenuItem_DadosEstatistica;
    }

    //
    public JMenuItem getjMenuItem_About() {
        return jMenuItemAbout;
    }
    public JMenuItem getjMenuItem_Config() {
        return jMenuItemConfig;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuFile;
    private javax.swing.JButton jButton_CalcularRota;
    private javax.swing.JButton jButton_DadosEstatistica;
    private javax.swing.JButton jButton_SimularRota;
    private javax.swing.JLabel jLabelSelecionar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVersao;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenuItem jMenuItem_CalcularRota;
    private javax.swing.JMenuItem jMenuItem_DadosEstatistica;
    private javax.swing.JMenuItem jMenuItem_Sair;
    private javax.swing.JMenuItem jMenuItem_SimularRota;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPanelSelection;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JSeparator jSeparatorTitulo;
    private javax.swing.JSeparator jSeparatorVersao;
    // End of variables declaration//GEN-END:variables
}
